import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "inverse-primary": "#b4c5ff",
        "surface": "#faf8ff",
        "secondary-container": "#d0e1fb",
        "on-background": "#131b2e",
        "inverse-surface": "#283044",
        "outline": "#737686",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-fixed-dim": "#b4c5ff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary": "#004ac6",
        "tertiary-container": "#bc4800",
        "primary-container": "#2563eb",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb596",
        "on-surface-variant": "#434655",
        "tertiary": "#943700",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-fixed": "#360f00",
        "background": "#faf8ff",
        "on-error": "#ffffff",
        "surface-tint": "#0053db",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-container": "#eaedff",
        "on-primary-fixed": "#00174b",
        "on-surface": "#131b2e",
        "on-primary-container": "#eeefff",
        "on-secondary-container": "#54647a",
        "tertiary-fixed": "#ffdbcd",
        "primary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-low": "#f2f3ff",
        "secondary": "#505f76",
        "on-tertiary-container": "#ffede6",
        "on-secondary-fixed-variant": "#38485d",
        "surface-dim": "#d2d9f4",
        "surface-variant": "#dae2fd",
        "surface-container-highest": "#dae2fd"
      },
    },
  },
  plugins: [forms],
};
export default config;
