# Generated by Django 5.2.14 on 2026-05-20 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100, verbose_name='patient name/initials')),
                ('patient_birth_date', models.DateField(verbose_name='patient birth date')),
                ('specialty', models.CharField(choices=[('CARDIOLOGIA', 'Cardiologia'), ('CIRURGIA_ROBOTICA', 'Cirurgia Robótica'), ('ODONTOLOGIA', 'Odontologia'), ('DOENCAS_RARAS', 'Doenças Raras'), ('OXIGENOTERAPIA', 'Oxigenoterapia')], max_length=50, verbose_name='specialty')),
                ('diagnostic_hypothesis', models.CharField(max_length=255, verbose_name='diagnostic hypothesis')),
                ('clinical_history', models.TextField(verbose_name='clinical history summary')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialista', models.ForeignKey(blank=True, limit_choices_to={'role': 'ESPECIALISTA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teleconsultas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(limit_choices_to={'role': 'SOLICITANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teleconsultation',
                'verbose_name_plural': 'teleconsultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teleconsultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='teleconsultations.teleconsultation')),
            ],
            options={
                'verbose_name': 'status history',
                'verbose_name_plural': 'status histories',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='feedback content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_registrados', to=settings.AUTH_USER_MODEL)),
                ('teleconsultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='teleconsultations.teleconsultation')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='AI confidence score')),
                ('ai_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI provider')),
                ('ai_threshold', models.FloatField(blank=True, null=True, verbose_name='AI threshold applied')),
                ('ai_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='AI validation timestamp')),
                ('teleconsultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='teleconsultations.teleconsultation')),
            ],
        ),
    ]
