# Generated by Django 5.2.14 on 2026-05-21 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='teleconsultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='teleconsultations.teleconsultation'),
        ),
    ]
