# Generated by Django 6.0.2 on 2026-05-24 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultations', '0003_globalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(default='VIEW_DETAILS', max_length=50)),
                ('teleconsultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='teleconsultations.teleconsultation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access log',
                'verbose_name_plural': 'access logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
