# Generated by Django 6.0.2 on 2026-05-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultations', '0004_accesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ai_score',
        ),
        migrations.AddField(
            model_name='attachment',
            name='patient_name_cache',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='teleconsultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='teleconsultations.teleconsultation'),
        ),
    ]
