# Generated by Django 5.2.14 on 2026-05-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultations', '0005_remove_attachment_ai_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI confidence score'),
        ),
    ]
